server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microsvc
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

management:
  tracing:
    sampling:
      probability: 1.0

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false

resilience4j.circuitbreaker.configs.default.registerHealthIndicator: false
resilience4j.ratelimiter.configs.instances.registerHealthIndicator: true

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instance:
      getSingleQuiz:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 100
        minimumNumberOfCalls: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 1
        slidingWindowType: COUNT_BASED
      getAllQuizes:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 100
        minimumNumberOfCalls: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 1
        slidingWindowType: COUNT_BASED
  retry:
    retryAspectOrder: 2
    instances:
      retryFallback:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.lang.RuntimeException
          - feign.FeignException
  ratelimiter:
    ratelimiterAspectOrder: 3
    instance:
      rateLimiterFallback:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s