server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microsvc
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

management:
  tracing:
    sampling:
      probability: 1.0